#project 'KotlinIOS.xcodeproj'
use_frameworks!
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KotlinIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  #use_modular_headers!

  # Pods for KotlinIOS
  pod "SwipeTransition"
  pod "SwipeTransitionAutoSwipeBack"      # if needed
  pod "SwipeTransitionAutoSwipeToDismiss" # if needed
  pod 'Kingfisher', '~> 5.0'
  pod 'SCLAlertView'

  pod 'SharedCode', :path => '/Users/jrein/AndroidStudioProjects/mpp-ios-android/SharedCode'

  target 'KotlinIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KotlinIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
